//
// Copyright 2026 Mikhail Kasianov
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file or at
// https://opensource.org/licenses/MIT.

import Foundation

public struct DefinitionCodeGenerator {
    public init() {}

    /// Turns a definition's JSON into a complete source file: validated, with
    /// the imports the generated struct needs — the form the build-tool plugin
    /// and the `scoutdb-codegen` executable emit.
    public func source(forJSON data: Data) throws -> String {
        let definition = try JSONDecoder().decode(EntityDefinition.self, from: data)
        try definition.validate()
        return "// Generated by scoutdb-codegen from '\(definition.entity)' v\(definition.version). Do not edit.\n\n"
            + "import Foundation\nimport ScoutDB\n\n" + source(for: definition) + "\n"
    }

    public func source(for definition: EntityDefinition) -> String {
        let typeName = camel(definition.entity, capitalized: true)
        let fields = definition.fields(at: definition.version)

        var lines = ["struct \(typeName): EntityRepresentable {"]
        lines.append("    static let entityName = \"\(definition.entity)\"")
        lines.append("")
        lines.append("    static func fieldName(for keyPath: PartialKeyPath<\(typeName)>) -> String? {")
        lines.append("        switch keyPath {")
        for field in fields {
            lines.append("        case \\\(typeName).\(camel(field.name)): \"\(field.name)\"")
        }
        lines.append("        default: nil")
        lines.append("        }")
        lines.append("    }")
        lines.append("")
        for field in fields {
            lines.append("    var \(camel(field.name)): \(swiftType(of: field.type))?")
        }
        lines.append("")
        lines.append("    init(record: EntityRecord) {")
        for field in fields {
            if Self.opaque(field.type) {
                lines.append("        \(camel(field.name)) = record.values[\"\(field.name)\"]")
            } else {
                lines.append("        \(camel(field.name)) = record[\"\(field.name)\"]")
            }
        }
        lines.append("    }")
        lines.append("")
        lines.append("    var recordValues: [String: RecordValue] {")
        lines.append("        var values: [String: RecordValue] = [:]")
        for field in fields {
            if Self.opaque(field.type) {
                lines.append("        values[\"\(field.name)\"] = \(camel(field.name))")
            } else {
                lines.append("        values[\"\(field.name)\"] = \(camel(field.name))?.recordValue")
            }
        }
        lines.append("        return values")
        lines.append("    }")
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    // The kinds with no native Swift counterpart stay as raw `RecordValue`s.
    // `.reference` is one of them: mapping it to `String` produced code that
    // read back nil (String decodes only `.string`) and threw `typeMismatch` on
    // write (a String encodes to `.string`, which no `.reference` field accepts).
    private static func opaque(_ type: FieldType) -> Bool {
        [.location, .asset, .locationList, .assetList, .reference].contains(type)
    }

    private func swiftType(of type: FieldType) -> String {
        switch type {
        case .string, .text: "String"
        case .int: "Int64"
        case .double: "Double"
        case .timestamp: "Date"
        case .bytes: "Data"
        case .reference: "RecordValue"
        case .stringList: "[String]"
        case .intList: "[Int64]"
        case .doubleList: "[Double]"
        case .timestampList: "[Date]"
        case .locationList: "RecordValue"
        case .assetList: "RecordValue"
        case .location: "RecordValue"
        case .asset: "RecordValue"
        }
    }

    private func camel(_ name: String, capitalized: Bool = false) -> String {
        let parts = name.split(separator: "_").map(String.init)
        guard let first = parts.first else { return name }
        let head = capitalized ? first.capitalized : first.lowercased()
        return head + parts.dropFirst().map(\.capitalized).joined()
    }
}
